### PR TITLE
Add more Validation to AuthenticationView

### PR DESCRIPTION
**Pull request by wasanderes94**
# Context

Since some of the validation in AuthenticationView has already been implemented, I've only added some additional validations in the same manner:
- Show Toast Message if  `password.length < 8`
- Show Toast Message if `name.isBlank()` since this leads to invalid User Input error
- Removing Whitespaces at the beginning and end of each field at creation of `registerBody` and `loginBody`
- Generating random UUID if `ID` field is empty

### CODE REVIEW

**Review by Morphclue — CHANGES_REQUESTED** [review]
When we talked about it `trim()` sounded like a good idea in theory.
The problem is that the server allows for users that are named `Mr Blank        `.
If someone would like to login with this name we wouldn't support this anymore.
Therefore i think we have to remove `trim()`.

Of course, I'm still open to arguments for using `trim()`.

**Comment by wasanderes94** [comment]
> When we talked about it `trim()` sounded like a good idea in theory. The problem is that the server allows for users that are named `Mr Blank `. If someone would like to login with this name we wouldn't support this anymore. Therefore i think we have to remove `trim()`.
> 
> Of course, I'm still open to arguments for using `trim()`.

If your point is the whitespace between `Mr` and `Blank`, it will be there after trim, since it is only removing whitespaces at the beginning and the end of the whole string. 
If your point is the whitespace at the end of  `Blank ` i`m not sure how common this case is. Even if there is a whitespace, i would say that 99% of those cases are not intended, since probably just had a typo. But i do not have any statistics about that, thats just a personal observation

**Review by Morphclue — APPROVED** [review]
You are right. This needs to be fixed on the server-side since no one handles usernames like that, so we shouldn't allow for user-creations like that. 

As of today, people like `Mr Blank    `  are no longer allowed to use our app!

**Comment by wasanderes94** [comment]
> You are right. This needs to be fixed on the server-side since no one handles usernames like that, so we shouldn't allow for user-creations like that.
> 
> As of today, people like `Mr Blank ` are no longer allowed to use our app!

Sorry `Mr Blank ` :(

**Pull request merged**
